### ISSUE TITLE
open sourced repo of paper "Block-Map-Based Localization in Large-Scale Environment" available?

### ISSUE THREAD

**Issue by narutojxl** [caleb-feng/Block_Map_from_Groundtruth#2]
Hello @YixFeng,
Is there some schedule of open sourced repo for "Block-Map-Based Localization in Large-Scale Environment", the [link](https://github.com/YixFeng/block_localization) is not available now.

**Comment by YixFeng** [comment]
Yes, some modifications need to be done. Now it’s a private repo and I plan
to release approximately in two months.

**Comment by narutojxl** [comment]
great!
