### ISSUE TITLE
M2DGR GT

### ISSUE THREAD

**Issue by XYJ88888** [caleb-feng/Block_Map_from_Groundtruth#3]
I had a serious problem generating BM maps using the GT file of the M2DGR and its bag: the maps were cluttered
M2DGR GT is TUM format, can you use it directly? Or is it because the GT2Lidar external reference is wrong?I used the sequence street_04
[street_04.txt](https://github.com/user-attachments/files/17567120/street_04.txt)
![2024-10-30 14-29-31 的屏幕截图](https://github.com/user-attachments/assets/5a9dad38-922f-4584-a447-33c6541250a5)

**Comment by YixFeng** [comment]
You need to postprocess the GT to make sure the first pose is an identity matrix and also transform the subsequent poses using the same transformation matrix.

**Comment by XYJ88888** [comment]
> You need to postprocess the GT to make sure the first pose is an identity matrix and also transform the subsequent poses using the same transformation matrix.您需要对GT进行后处理，以确保第一个姿势是单位矩阵，并使用相同的变换矩阵变换后续姿势。
Thank you for your reply. I have also converted my gt.txt file, but it still doesn't work well. Here are my txt files., or could you provide a txt and config as a reference? Looking forward to your reply.
The external parameters are UBLOX and Xsens GNSS in M2DGR calibration_desults.txt
% Extrinsic [to LIDAR]
data: [1., 0., 0., -0.09825,
0., 1, 0., 0.00582, 
0., 0., 1., 0.72673]

**Comment by XYJ88888** [comment]
[Uploading street_04.txt…]()

**Comment by XYJ88888** [comment]
Thank you for your reply. I have also converted my gt.txt, but it still doesn't work well. Here is my txt, or could you provide a txt and config as a reference? Looking forward to your reply.
The external parameters are UBLOX and Xsens GNSS in M2DGR calibration_desults.txt
% Extrinsic [to LIDAR]
data: [1., 0., 0., -0.09825,
0., 1, 0., 0.00582, 
0., 0., 1., 0.72673]
[Uploading street_04.txt…]()

**Comment by XYJ88888** [comment]
Thank you for your reply. I have also converted my gt.txt, but it still doesn't work well. Here is my txt, or could you provide a txt and config as a reference? Looking forward to your reply.
The external parameters are UBLOX and Xsens GNSS in M2DGR calibration_desults.txt
% Extrinsic [to LIDAR]
data: [1., 0., 0., -0.09825,
0., 1, 0., 0.00582, 
0., 0., 1., 0.72673]
![2024-10-30 16-47-23 的屏幕截图](https://github.com/user-attachments/assets/da991f21-585c-4285-b38b-1fa6adfc8f4e)

**Comment by XYJ88888** [comment]
Thank you for your reply. I have also converted my gt.txt, but it still doesn't work well. Here is my txt, or could you provide a txt and config as a reference? Looking forward to your reply.
The external parameters are UBLOX and Xsens GNSS in M2DGR calibration_desults.txt
% Extrinsic [to LIDAR]
data: [1., 0., 0., -0.09825,
0., 1, 0., 0.00582, 
0., 0., 1., 0.72673]
[street_04.txt](https://github.com/user-attachments/files/17568708/street_04.txt)

**Comment by YixFeng** [comment]
In the branch 'tolidar', there is a script named process_gt_m2dgr.py which would be helpful for you. You can have a try

**Comment by YixFeng** [comment]
@XYJ88888 These are GT files I use. 
[street_01_after.txt](https://github.com/user-attachments/files/17609919/street_01_after.txt)
[street_02_after.txt](https://github.com/user-attachments/files/17609921/street_02_after.txt)
